# Generated by Django 5.2.8 on 2026-06-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='sevico',
            new_name='servico',
        ),
    ]
