# Generated by Django 5.2.8 on 2026-07-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contato_alter_recurso_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='twitter',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, verbose_name='LinkedIn'),
        ),
    ]
